/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CKzg4844JNI */

#ifndef _Included_CKzg4844JNI
#define _Included_CKzg4844JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CKzg4844JNI
 * Method:    loadTrustedSetup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CKzg4844JNI_loadTrustedSetup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CKzg4844JNI
 * Method:    freeTrustedSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CKzg4844JNI_freeTrustedSetup
  (JNIEnv *, jclass);

/*
 * Class:     CKzg4844JNI
 * Method:    computeAggregateKzgProof
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CKzg4844JNI_computeAggregateKzgProof
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     CKzg4844JNI
 * Method:    verifyAggregateKzgProof
 * Signature: ([B[BI[B)Z
 */
JNIEXPORT jboolean JNICALL Java_CKzg4844JNI_verifyAggregateKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     CKzg4844JNI
 * Method:    blobToKzgCommitment
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CKzg4844JNI_blobToKzgCommitment
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     CKzg4844JNI
 * Method:    verifyKzgProof
 * Signature: ([B[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_CKzg4844JNI_verifyKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
