/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ethereum_ckzg4844_CKzg4844JNI */

#ifndef _Included_ethereum_ckzg4844_CKzg4844JNI
#define _Included_ethereum_ckzg4844_CKzg4844JNI
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    loadTrustedSetup
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_loadTrustedSetup(JNIEnv *, jclass, jstring);

  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    freeTrustedSetup
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_freeTrustedSetup(JNIEnv *, jclass);

  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    computeAggregateKzgProof
   * Signature: ([BJ)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_computeAggregateKzgProof(JNIEnv *, jclass, jbyteArray, jlong);

  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    verifyAggregateKzgProof
   * Signature: ([B[BJ[B)Z
   */
  JNIEXPORT jboolean JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_verifyAggregateKzgProof(JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jbyteArray);

  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    blobToKzgCommitment
   * Signature: ([B)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_blobToKzgCommitment(JNIEnv *, jclass, jbyteArray);

  /*
   * Class:     ethereum_ckzg4844_CKzg4844JNI
   * Method:    verifyKzgProof
   * Signature: ([B[B[B[B)Z
   */
  JNIEXPORT jboolean JNICALL Java_ethereum_ckzg4844_CKzg4844JNI_verifyKzgProof(JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
