version: "2"
linters:
  default: all
  disable:
    # just whining
    - copyloopvar                       # go>=1.22
    - cyclop
    - dupword
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - intrange                          # go>=1.22
    - lll
    - mnd
    - nestif
    - nlreturn
    - varnamelen
    - whitespace
    - wsl
    # auto-generation artefact
    - dupl
    # maybe some day...
    - godox
    - maintidx
    # maybe some day in tests...
    - forcetypeassert
    - nonamedreturns
    - perfsprint
    - testpackage
    # 78 active linters remaining including gosec, gosimple, govet, etc.
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: cognitive-complexity    # similar to 'gocognit' above
          disabled: true
        - name: cyclomatic              # similar to 'cyclop' & 'gocyclo' above
          disabled: true
        - name: empty-block
          disabled: true
        - name: empty-lines
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length         # similar to 'funlen' above
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: line-length-limit       # similar to 'lll' above
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: receiver-naming
          disabled: true
        - name: var-naming
          disabled: true
        - name: unchecked-type-assertion # similar to 'forcetypeassert' above
          disabled: true
        - name: unexported-naming
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Println
            - fmt.Printf
        - name: use-any                 # applicable to go>=1.18 only
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
