queries:
  - include: "*"
  - exclude: cpp/unused-static-function
  - exclude: cpp/include-non-header
  - exclude: cs/call-to-unmanaged-code
  - exclude: cs/unmanaged-code

extraction:
  cpp:
    index:
      build_command:
      - ./build.sh -m32
  go:
    index:
      build_command:
      - (cd bindings/go; go test -c)

  csharp:
    index:
      nuget_restore: false

