name: CKZG tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          cd src
          make blst
          make
      - name: Test
        run: |
          cd src
          make test
      - name: Install LLVM
        uses: egor-tensin/setup-clang@v1
      - name: Generate coverage report
        run: |
          cd src
          make test_cov
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.html
      - name: Check coverage
        run: |
          cd src
          make test_cov
          make test_cov | grep TOTAL | awk '{print $4" "$7" "$10}' | grep -q "100.00% 100.00% 100.00%"
