name: Formatting tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check formatting
        run: |
          cd src
          make format
          git diff --exit-code
