name: Go bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: |
          cd bindings/go
          go test .
      - name: Check headers
        run: |
          cmp blst/bindings/blst.h bindings/go/blst_headers/blst.h
          cmp blst/bindings/blst_aux.h bindings/go/blst_headers/blst_aux.h
