name: Go bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fuzz-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        run: cd src && make blst
      - name: Test
        run: cd bindings/go && CC=clang go test .
