name: Go bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup
        run: cd src && make blst
      - name: Test
        run: cd bindings/go && CC=clang go test .
      - name: Build plugin
        run: cd bindings/go && CC=clang go build -buildmode=plugin -o gockzg.so
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: bindings/go/gockzg.so