name: Python bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py_ecc
      - name: Build BLST
        run: |
          cd src
          make blst
      - name: Build CKZG
        run: |
          cd src
          make
      - name: Build Python bindings
        run: |
          cd bindings/python
          make install
      - name: Test
        run: |
          cd bindings/python
          make test
      - name: ECC test
        run: |
          cd bindings/python
          make ecc_test
