name: Rust bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-rust-bindings:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get latest version of stable rust
        run: |
          rustup update stable
      - name: Build and Test (mainnet preset)
        run: |
          cd bindings/rust
          cargo clean
          cargo test --all --release --tests
      - name: Build and Test (minimal preset)
        run: |
          cd bindings/rust
          cargo clean
          cargo test --all --release --features="minimal-spec" --tests
