name: Trusted Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download
        run: wget -O trusted_setup.json https://github.com/ethereum/consensus-specs/raw/dev/presets/mainnet/trusted_setups/trusted_setup_4096.json
      - name: Convert
        run: python3 ./scripts/convert_trusted_setup.py --input trusted_setup.json --output trusted_setup.txt
      - name: Compare
        run: cmp src/trusted_setup.txt trusted_setup.txt
