name: Trusted Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download minimal preset
        run: wget https://github.com/ethereum/consensus-specs/raw/dev/presets/minimal/trusted_setups/testing_trusted_setups.json
      - name: Convert minimal to txt
        run: python3 ./scripts/convert_trusted_setup.py --json testing_trusted_setup.json --text trusted_setup_minimal.txt
      - name: Compare to existing file
        run: cmp src/trusted_setup_4.txt trusted_setup_minimal.txt

      - name: Download mainnet preset
        run: wget https://github.com/ethereum/consensus-specs/raw/dev/presets/mainnet/trusted_setups/testing_trusted_setups.json
      - name: Convert mainnet to txt
        run: python3 ./scripts/convert_trusted_setup.py --json testing_trusted_setup.json --text trusted_setup_mainnet.txt
      - name: Compare to existing file
        run: cmp src/trusted_setup.txt trusted_setup_mainnet.txt
