name: Zig
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Check blst dependency hash
        run: make zig-check
      - name: Install yq (Linux)
        if: runner.os == 'Linux'
        run: sudo snap install yq
      - name: Install yq (macOS)
        if: runner.os == 'macOS'
        run: brew install yq
      - name: Install yq (Windows)
        if: runner.os == 'Windows'
        run: choco install yq
      - name: Convert test vectors from YAML to JSON
        run: find tests -name "data.yaml" -exec sh -c 'yq -o=json "$1" > "$(dirname "$1")/data.json"' _ {} \;
      - name: Test
        run: zig build test
